apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/nv-wa-skill
    newTag: 69d99a651f8a8c2c8b4afd6f29f640e1c7fa5a14
