apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/nv-wa-skill
    newTag: d95b998321f43e682344038f5a9ea26af1db0f48
